### ISSUE TITLE
Suggest supporting surface-mount PLCC sockets

### ISSUE THREAD

**Issue by terrabite3** [rhalkyard/SEthernet#16]
I'm currently using surface-mount PLCC sockets for a project, specifically this one:

https://www.mouser.com/ProductDetail/575-946817

I've found that the footprint of the socket is the same as for soldering a PLCC directly to the board, except that it requires more space around the pads. If it's feasible, I suggest leaving room so that you or others will have the option of using this type of socket.

I'm not likely to build this myself, so I don't have any skin in the game. I just wanted to pass on a tip in case it might be useful.

**Comment by rhalkyard** [comment]
Thanks! I thought about it, but I've always found them tricky to hand-solder, and Revision 0 was only ever intended to be a prototype that I could throw together myself to prove the concept out before cleaning the design up for production.

For my next revision of the board, I plan to ditch the GALs for a JTAG-programmable CPLD (#5), and write a tool to reflash the declaration ROM in-system (#6), so no sockets will be required - this will have the added benefit of making automated assembly (e.g. by JLCPCB's assembly service) much easier, since it won't require any preprogrammed parts.
